import React,{useEffect,useState} from 'react';
import {Alert,ScrollView,Switch,View} from 'react-native';
import {useBrief} from '../lib/appContext';import {C} from '../theme/tokens';
import {Card,Field,Heading,Icon,Primary,Txt,Tap} from '../components/Ui';
import {deleteLocalFile,pickModel,pickResume,readResumeText} from '../lib/imports';import {benchmarkModel,configureModel,modelPath,releaseModel} from '../lib/ai';
import * as Sharing from 'expo-sharing';
export function ResumeScreen(){const {profile,updateProfile}=useBrief();const [edit,setEdit]=useState(false),[busy,setBusy]=useState(false),[name,setName]=useState(profile.name),[skills,setSkills]=useState(profile.skills),[education,setEducation]=useState(profile.education),[experience,setExperience]=useState(profile.experience),[goals,setGoals]=useState(profile.goals);
 async function attach(){setBusy(true);try{const uri=await pickResume();if(!uri)return;let text='';if(uri.endsWith('.pdf'))try{text=await readResumeText(uri);}catch(e){Alert.alert('Resume saved','Text extraction needs a compatible native build. Enter your experience and skills manually so AI can use them.');}else Alert.alert('Resume saved','DOCX text extraction is not implemented yet. Please fill in the career summary below.');if(profile.resumeUri&&profile.resumeUri!==uri)await deleteLocalFile(profile.resumeUri);await updateProfile({...profile,resumeUri:uri,useResumeForAI:true,resumeText:text});}catch(e){Alert.alert('Resume import failed',String(e));}finally{setBusy(false);}}
 async function openResume(){if(!profile.resumeUri)return;try{await Sharing.shareAsync(profile.resumeUri);}catch(e){Alert.alert('Cannot open file',String(e));}}
 async function save(){await updateProfile({...profile,name,skills,education,experience,goals});setEdit(false);}
 return <ScrollView contentContainerStyle={{padding:18,paddingBottom:125,gap:15}}><Heading>Resume</Heading>
 <Tap onPress={()=>profile.resumeUri?void openResume():void attach()} style={{height:310,borderRadius:20,backgroundColor:C.pale2,borderColor:C.line,borderWidth:1,padding:17,alignItems:'center',justifyContent:'center'}}>
 {profile.resumeUri?<View style={{width:'88%',height:'95%',backgroundColor:C.white,borderRadius:5,padding:18,shadowColor:'#142742',shadowOpacity:0.09,shadowRadius:12,elevation:3,gap:9}}><Txt size={19} bold>{profile.name||'Your Name'}</Txt><Txt size={12} color={C.blue}>CAREER PROFILE</Txt><View style={{height:1,backgroundColor:C.line}}/><Txt bold size={10}>EXPERIENCE</Txt><Txt size={11} color={C.muted} style={{maxHeight:60}}>{profile.experience||profile.resumeText.slice(0,140)||'Imported resume available to open'}</Txt><Txt bold size={10}>EDUCATION</Txt><Txt color={C.muted} size={11} style={{maxHeight:33}}>{profile.education||'Add education in your summary'}</Txt><Txt bold size={10}>SKILLS</Txt><Txt size={11} color={C.muted} style={{maxHeight:45}}>{profile.skills||'Add skills in your summary'}</Txt></View>:<><Icon name="document-attach-outline" color={C.blue} size={38}/><Txt bold style={{marginTop:12}}>Tap to attach your resume</Txt><Txt color={C.muted} size={12}>PDF or DOCX · Stored on your device</Txt></>}
 </Tap>
 {profile.resumeUri&&<View style={{flexDirection:'row',gap:8}}><View style={{flex:1}}><Primary secondary label="Open file" onPress={()=>void openResume()}/></View><View style={{flex:1}}><Primary secondary label="Replace" onPress={()=>void attach()}/></View><View style={{flex:1}}><Primary secondary label="Remove" onPress={()=>Alert.alert('Remove resume?','Remove the document and its extracted text?', [{text:'Cancel'},{text:'Remove',style:'destructive',onPress:()=>void deleteLocalFile(profile.resumeUri).then(()=>updateProfile({...profile,resumeUri:'',resumeText:''}))}])}/></View></View>}
 <Card><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:10}}><Txt bold size={17}>Resume summary</Txt><Tap onPress={()=>setEdit(!edit)}><Txt color={C.blue}>{edit?'Cancel':'Edit'}</Txt></Tap></View>
 {edit?<><Field label="Name" value={name} onChangeText={setName}/><Field label="Experience" multiline value={experience} onChangeText={setExperience}/><Field label="Education" multiline value={education} onChangeText={setEducation}/><Field label="Skills" multiline value={skills} onChangeText={setSkills}/><Field label="Career goals" multiline value={goals} onChangeText={setGoals}/><Primary label="Save summary" onPress={()=>void save()}/></>:
 <View style={{gap:12}}>{[{icon:'briefcase-outline',text:profile.experience||'Add professional experience'},{icon:'school-outline',text:profile.education||'Add education'},{icon:'list-outline',text:profile.skills||'Add skills'},{icon:'location-outline',text:profile.goals||'Add career interests'}].map((x,i)=><View key={i} style={{flexDirection:'row',gap:12,alignItems:'flex-start'}}><Icon name={x.icon} color={C.muted}/><View style={{flex:1}}><Txt color={C.muted} size={12}>{x.text}</Txt></View></View>)}</View>}
 </Card>
 <Card><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10}}><View style={{flex:1}}><Txt bold>Use imported resume in Brief AI</Txt><Txt color={C.muted} size={11}>Only on this device. You can switch this off anytime.</Txt></View><Switch value={profile.useResumeForAI} onValueChange={x=>void updateProfile({...profile,useResumeForAI:x})} trackColor={{true:C.blue,false:C.line}}/></View></Card>
 <Txt color={C.muted} size={11}>The preview above is a visual summary, not a rendered PDF. “Open file” uses the system file viewer/share sheet. Digitally generated PDF text is extracted locally when supported; scanned PDFs and DOCX need manual summary entry in this starter.</Txt>
 </ScrollView>;
}
export function NotificationsScreen(){return <ScrollView contentContainerStyle={{padding:18,paddingBottom:110,gap:15}}><Heading>Notifications</Heading><Card><Icon name="notifications-outline" color={C.blue} size={26}/><Txt bold>Nothing new</Txt><Txt color={C.muted}>Your events are in Calendar. Local reminder notifications are on the roadmap; this screen does not pretend reminders have been scheduled.</Txt></Card></ScrollView>}
export function SettingsScreen(){const {profile,updateProfile,replayOnboarding}=useBrief();const [model,setModel]=useState(''),[busy,setBusy]=useState(''),[name,setName]=useState(profile.name),[result,setResult]=useState('');
 useEffect(()=>{void modelPath().then(setModel);},[]);
 async function importModel(){setBusy('Importing model… large files can take a minute.');setResult('');try{await releaseModel();const uri=await pickModel();if(!uri)return;await configureModel(uri);setModel(uri);setResult('Model imported. Tap “Test local model” to load it.');}catch(e){Alert.alert('Import failed',(e as Error).message);}finally{setBusy('');}}
 async function testModel(){setBusy('Loading model… 0%');setResult('');try{const r=await benchmarkModel(p=>setBusy(`Loading model… ${Math.round(p)}%`));setResult(`Ready on this device. Load ${(r.loadMs/1000).toFixed(1)} s · ${r.tokensPerSec.toFixed(1)} tokens/s.\nSample: “${r.sample}”`);}catch(e){setResult('');Alert.alert('Model failed',(e as Error).message);}finally{setBusy('');}}
 return <ScrollView contentContainerStyle={{padding:18,paddingBottom:120,gap:18}}><Heading>Settings</Heading>
 <Card><Txt bold>Display name</Txt><Field label="Name" value={name} onChangeText={setName}/><Primary secondary label="Save name" onPress={()=>void updateProfile({...profile,name})}/></Card>
 <Card><Txt bold>On-device AI model</Txt><Txt color={C.muted} size={12} style={{marginVertical:9}}>{model?'GGUF model installed locally':'No model installed yet. Chat and Mock will ask you to install a model rather than secretly using a cloud service.'}</Txt><Primary label="Import GGUF model" disabled={!!busy} onPress={()=>void importModel()}/><View style={{height:8}}/><Primary label="Test local model" secondary disabled={!!busy||!model} onPress={()=>void testModel()}/>{!!(busy||result)&&<Txt size={12} color={busy?C.muted:C.green} style={{marginTop:10}}>{busy||result}</Txt>}</Card>
 <Card><Txt bold>Privacy</Txt><Txt color={C.muted} style={{marginTop:8}}>Applications, messages, and profile data are saved in your device's local SQLite database. Discovery requires an internet connection. No account or cloud LLM is configured.</Txt></Card>
 <Card style={{gap:10}}><Txt bold>Welcome tour</Txt><Txt color={C.muted} size={12}>See the introduction again. Your jobs and profile are kept.</Txt><Primary secondary label="Show onboarding again" onPress={()=>void replayOnboarding()}/></Card>
 </ScrollView>;
}
