import React,{useMemo,useState} from 'react';import {Alert,Pressable,ScrollView,View} from 'react-native';
import {useBrief} from '../lib/appContext';import {C} from '../theme/tokens';import {Card,Field,Heading,Icon,Primary,SectionTitle,Txt} from '../components/Ui';import {uid} from '../lib/db';
export function CalendarScreen(){const {events,applications,putEvent,removeEvent}=useBrief();const [month,setMonth]=useState(new Date().getMonth()),[year,setYear]=useState(new Date().getFullYear()),[day,setDay]=useState(new Date().getDate()),[adding,setAdding]=useState(false),[title,setTitle]=useState(''),[time,setTime]=useState('10:00'),[notes,setNotes]=useState('');
 const first=new Date(year,month,1).getDay(),length=new Date(year,month+1,0).getDate();const cells=[...Array(first).fill(0),...Array.from({length},(_,i)=>i+1)];
 const selected=`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
 const monthLabel=new Date(year,month,1).toLocaleDateString('en-US',{month:'long',year:'numeric'});
 const upcoming=useMemo(()=>events.slice().sort((a,b)=>a.date.localeCompare(b.date)),[events]);
 function move(delta:number){const d=new Date(year,month+delta,1);setYear(d.getFullYear());setMonth(d.getMonth());setDay(1)}
 async function add(){if(!title.trim())return Alert.alert('Add event title');await putEvent({id:uid('event'),applicationId:null,title:title.trim(),date:selected+'T'+time+':00',notes});setAdding(false);setTitle('');setNotes('');}
 return <ScrollView contentContainerStyle={{padding:18,paddingBottom:125,gap:15}}><Heading>Calendar</Heading><Txt color={C.muted}>Stay on top of interviews, follow-ups, and deadlines.</Txt>
 <Card><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><Pressable onPress={()=>move(-1)}><Icon name="chevron-back" color={C.blue}/></Pressable><Txt bold>{monthLabel}</Txt><Pressable onPress={()=>move(1)}><Icon name="chevron-forward" color={C.blue}/></Pressable></View>
 <View style={{flexDirection:'row',flexWrap:'wrap'}}>{['S','M','T','W','T','F','S'].map((d,i)=><View key={i} style={{width:'14.285%',alignItems:'center',paddingVertical:6}}><Txt size={11} color={C.muted}>{d}</Txt></View>)}
 {cells.map((n,i)=><Pressable onPress={()=>n&&setDay(n)} key={i} style={{width:'14.285%',height:42,alignItems:'center',justifyContent:'center'}}><View style={{height:32,width:32,backgroundColor:n===day?C.blue:'transparent',borderRadius:17,justifyContent:'center',alignItems:'center'}}><Txt color={n===day?C.white:n?C.ink:C.soft} size={13}>{n||''}</Txt>{n>0&&events.some(e=>e.date.slice(0,10)===`${year}-${String(month+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`)&&<View style={{backgroundColor:n===day?C.white:C.blue,width:4,height:4,borderRadius:2}}/>}</View></Pressable>)}
 </View></Card>
 <SectionTitle right="Add event" onRight={()=>setAdding(!adding)}>Upcoming events</SectionTitle>
 {adding&&<Card><Txt bold>New event · {selected}</Txt><Field label="Event" value={title} onChangeText={setTitle} placeholder="Interview with..."/><Field label="Time (24h HH:MM)" value={time} onChangeText={setTime}/><Field label="Notes" value={notes} onChangeText={setNotes}/><Primary label="Save event" onPress={()=>void add()}/></Card>}
 {upcoming.filter(e=>e.date.slice(0,10)>=new Date().toISOString().slice(0,10)).length===0&&<Card><Txt color={C.muted}>No upcoming events yet. Add interviews and deadlines to keep track.</Txt></Card>}
 {upcoming.filter(e=>e.date.slice(0,10)>=new Date().toISOString().slice(0,10)).map(e=><Pressable key={e.id} onLongPress={()=>Alert.alert('Delete event?',e.title,[{text:'Cancel'},{text:'Delete',style:'destructive',onPress:()=>void removeEvent(e.id)}])} style={{flexDirection:'row',gap:12,alignItems:'center',borderRadius:17,backgroundColor:C.white,padding:13,borderWidth:1,borderColor:C.line}}><View style={{width:45,alignItems:'center'}}><Txt size={10} color={C.blue}>{new Date(e.date).toLocaleDateString('en-US',{month:'short'}).toUpperCase()}</Txt><Txt size={23} bold>{new Date(e.date).getDate()}</Txt></View><View style={{flex:1}}><Txt bold>{e.title}</Txt><Txt color={C.muted} size={12}>{e.date.replace('T',' · ').slice(0,16)}</Txt><Txt color={C.muted} size={11}>{e.notes}</Txt></View><Icon name="calendar-outline" color={C.blue}/></Pressable>)}
 </ScrollView>;
}
