import React,{useEffect,useRef,useState} from 'react';import {Alert,Image,ScrollView,TextInput,View} from 'react-native';
import {KeyboardAvoidingView} from 'react-native-keyboard-controller';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import Reanimated,{FadeIn} from 'react-native-reanimated';
import {useBrief} from '../lib/appContext';import {uid,listMessages,saveMessage} from '../lib/db';import {askBrief,suggestBriefQuestions,supportsVision,MODEL_MISSING} from '../lib/ai';import {pickJobImage,importChatImage} from '../lib/imports';import {C} from '../theme/tokens';import {Heading,Icon,Mascot,Txt,useKeyboardVisible,Tap} from '../components/Ui';import type {Message} from '../types';
import {LiveMascot} from '../components/LiveMascot';
import {InlineError,MessageBubble,ModelSetupCard,ThinkingBubble,TypingDots,useModelInstalled} from '../components/States';
import {EASE_OUT} from '../theme/motion';
export function ChatScreen(){const {profile,applications,chatJob,go}=useBrief();const thread=chatJob?'job:'+chatJob.id:'general';
 const [messages,setMessages]=useState<Message[]>([]),[entry,setEntry]=useState(''),[imageUri,setImageUri]=useState(''),[suggestions,setSuggestions]=useState<string[]>([]),[suggestionsBusy,setSuggestionsBusy]=useState(false),[loadedThread,setLoadedThread]=useState(''),[visionReady,setVisionReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const scroll=useRef<ScrollView>(null),suggestionCycle=useRef(0);
 const insets=useSafeAreaInsets();const kb=useKeyboardVisible();
 const openedAt=useRef(new Date().toISOString()).current; // messages newer than this animate in; history doesn't
 const installed=useModelInstalled();const noModel=installed===false||error===MODEL_MISSING;
 const aiReady=installed===true&&!noModel;
 useEffect(()=>{let active=true;setLoadedThread('');setMessages([]);setError('');setImageUri('');setSuggestions([]);setSuggestionsBusy(false);void listMessages(thread).then(rows=>{if(active){setMessages(rows);setLoadedThread(thread);}}).catch(e=>{if(active)setError((e as Error).message);});return()=>{active=false};},[thread]);
 useEffect(()=>{if(!aiReady){setVisionReady(false);return;}let active=true;void supportsVision().then(v=>{if(active)setVisionReady(v);}).catch(()=>{if(active)setVisionReady(false);});return()=>{active=false};},[aiReady]);
 useEffect(()=>{if(loadedThread!==thread||!aiReady)return;const latest=[...messages].reverse().find(m=>m.role==='assistant');if(latest?.suggestions?.length){setSuggestions(latest.suggestions);return;}let active=true;const cycle=++suggestionCycle.current;setSuggestionsBusy(true);void suggestBriefQuestions(profile,applications,messages,chatJob||undefined).then(xs=>{if(active&&suggestionCycle.current===cycle)setSuggestions(xs);}).catch(()=>{}).finally(()=>{if(active&&suggestionCycle.current===cycle)setSuggestionsBusy(false);});return()=>{active=false;suggestionCycle.current++;};},[loadedThread,thread,aiReady]);
 /** Asks the local model for a reply and the next conversation-specific questions in one pass. */
 async function reply(q:string,history:Message[],image?:string){setError('');setBusy(true);
  try{const out=await askBrief(q,profile,applications,history,chatJob||undefined,image);let next=out.suggestions;if(!next.length){const turn:Message[]=[...history,{id:'current-user',thread,role:'user',content:q,createdAt:'',imageUri:image},{id:'current-answer',thread,role:'assistant',content:out.answer,createdAt:''}];try{next=await suggestBriefQuestions(profile,applications,turn,chatJob||undefined);}catch{}}
   const answer:Message={id:uid('msg'),thread,role:'assistant',content:out.answer,suggestions:next,createdAt:new Date().toISOString()};await saveMessage(answer);setMessages(old=>[...old,answer]);setSuggestions(next);}
  catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function attachImage(){if(!aiReady||!visionReady||busy)return;try{const picked=await pickJobImage();if(picked)setImageUri(await importChatImage(picked));}catch(e){Alert.alert('Couldn’t add image',(e as Error).message);}}
 async function send(text=entry){const q=text.trim(),attachment=imageUri;if((!q&&!attachment)||busy||!aiReady||(attachment&&!visionReady))return;suggestionCycle.current++;setSuggestionsBusy(false);const prompt=q||'Describe this image and suggest how it could help with my job search.';setEntry('');setImageUri('');setSuggestions([]);const m:Message={id:uid('msg'),thread,role:'user',content:prompt,imageUri:attachment||undefined,createdAt:new Date().toISOString()};const previous=messages;setMessages(old=>[...old,m]);await saveMessage(m);await reply(prompt,previous,attachment||undefined);}
 function retry(){const i=messages.map(m=>m.role).lastIndexOf('user');if(i>=0&&!busy){suggestionCycle.current++;setSuggestionsBusy(false);setSuggestions([]);void reply(messages[i].content,messages.slice(0,i),messages[i].imageUri);}}
 return <KeyboardAvoidingView style={{flex:1}} behavior="padding" keyboardVerticalOffset={insets.top+59}>
 <View style={{paddingHorizontal:18,paddingBottom:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><View style={{flex:1}}><Heading>Ask Brief</Heading><Txt color={C.muted} size={12} style={{flexShrink:1}}>{chatJob?chatJob.title+' · '+chatJob.company:'Your on-device job search companion'}</Txt></View>{!kb&&<View style={{backgroundColor:C.pale,borderRadius:45,padding:6}}><LiveMascot size={66} mood={busy?'question':error?'sad':'happy'} label={busy?'Brief is thinking':'Brief, the mascot'}/></View>}</View>
 <ScrollView ref={scroll} keyboardShouldPersistTaps="handled" onContentSizeChange={()=>scroll.current?.scrollToEnd({animated:true})} contentContainerStyle={{paddingHorizontal:16,paddingBottom:12,gap:12,flexGrow:1,justifyContent:'flex-end'}}>
 {messages.length===0&&!noModel&&<View style={{alignItems:'center',gap:6,paddingHorizontal:20,paddingBottom:8}}>
  <Txt bold size={17} style={{textAlign:'center'}}>{chatJob?'Ask about this job':'Ask me about your job hunt'}</Txt>
  <Txt size={14} color={C.muted} style={{textAlign:'center',lineHeight:20}}>{chatJob?'Red flags, what to ask HR, or whether you’re a fit — answers use this job’s description.':'Your saved jobs, red flags, your resume, or interview prep.'} Your messages stay on this phone.</Txt>
 </View>}
 {messages.map(m=><MessageBubble key={m.id} role={m.role} text={m.content} imageUri={m.imageUri} animate={m.createdAt>openedAt}/>)}
 {busy&&<ThinkingBubble/>}
 {noModel&&<ModelSetupCard feature="Ask Brief" onOpenSettings={()=>go('settings')}/>}
 {!!error&&!noModel&&<InlineError message={error} onRetry={retry}/>}
 </ScrollView>
 <View style={{paddingHorizontal:15,gap:8,paddingBottom:kb?8:82}}>
 {(aiReady&&suggestions.length>0)&&<ScrollView horizontal keyboardShouldPersistTaps="handled" showsHorizontalScrollIndicator={false} style={{flexGrow:0}} contentContainerStyle={{gap:7}}>{suggestions.map((x,i)=><Reanimated.View key={`${thread}-${i}-${x}`} entering={FadeIn.duration(180).easing(EASE_OUT)}><Tap accessibilityRole="button" disabled={busy} onPress={()=>void send(x)} style={{minHeight:40,justifyContent:'center',borderRadius:22,backgroundColor:C.pale,paddingHorizontal:12}}><Txt color={C.blue} size={12}>{x}</Txt></Tap></Reanimated.View>)}</ScrollView>}
 {aiReady&&suggestionsBusy&&suggestions.length===0&&<View accessible accessibilityLabel="Brief is preparing question ideas" style={{height:32,alignItems:'flex-start',justifyContent:'center',paddingLeft:8}}><TypingDots/></View>}
 {!!imageUri&&<View style={{flexDirection:'row',alignItems:'center',gap:9,alignSelf:'flex-start',padding:6,backgroundColor:C.white,borderRadius:14,borderWidth:1,borderColor:C.line}}><Image source={{uri:imageUri}} style={{width:52,height:52,borderRadius:9}}/><Txt size={12} color={C.muted} style={{maxWidth:160}} numberOfLines={1}>Image attached</Txt><Tap accessibilityRole="button" accessibilityLabel="Remove attached image" onPress={()=>setImageUri('')} style={{width:36,height:36,alignItems:'center',justifyContent:'center'}}><Icon name="close" color={C.muted}/></Tap></View>}
 <View style={{backgroundColor:C.white,borderRadius:28,borderWidth:1,borderColor:C.line,padding:6,flexDirection:'row',alignItems:'center',gap:5}}>
 <Tap accessibilityRole="button" accessibilityLabel="Add image" accessibilityHint={visionReady?'Choose an image to discuss with Brief':'Images need a compatible local vision model and projector'} disabled={!aiReady||!visionReady||busy} onPress={()=>void attachImage()} style={{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:C.pale2,opacity:aiReady&&visionReady&&!busy?1:0.42}}><Icon name="add" size={24} color={C.blue}/></Tap>
 <TextInput accessibilityLabel="Message Brief" editable={aiReady} value={entry} onChangeText={setEntry} placeholder={!aiReady?(noModel?'Set up on-device AI to chat':'Checking on-device AI…'):'Message Brief...'} placeholderTextColor={C.soft} style={{padding:8,flex:1,color:C.ink,maxHeight:120}} multiline/>
 <Tap accessibilityRole="button" accessibilityLabel="Send" disabled={busy||!aiReady||(!entry.trim()&&!imageUri)} onPress={()=>void send()} style={{width:44,height:44,backgroundColor:C.blue,opacity:busy||!aiReady||(!entry.trim()&&!imageUri)?.5:1,borderRadius:22,alignItems:'center',justifyContent:'center'}}><Icon name="arrow-up" color={C.white}/></Tap></View>
 </View></KeyboardAvoidingView>;
}
