import React,{useEffect,useRef,useState} from 'react';import {ActivityIndicator,KeyboardAvoidingView,Pressable,ScrollView,TextInput,View} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {useBrief} from '../lib/appContext';import {uid,listMessages,saveMessage} from '../lib/db';import {askBrief,MODEL_MISSING} from '../lib/ai';import {C} from '../theme/tokens';import {Card,Heading,Icon,Mascot,Primary,Txt,useKeyboardVisible} from '../components/Ui';import type {Message} from '../types';
const CHIPS=['What should I ask?','Is this a red flag?','Am I qualified?'];
export function ChatScreen(){const {profile,applications,chatJob,go}=useBrief();const thread=chatJob?'job:'+chatJob.id:'general';
 const [messages,setMessages]=useState<Message[]>([]),[entry,setEntry]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const scroll=useRef<ScrollView>(null);
 const insets=useSafeAreaInsets();const kb=useKeyboardVisible();
 useEffect(()=>{setError('');void listMessages(thread).then(setMessages);},[thread]);
 async function send(text=entry){const q=text.trim();if(!q||busy)return;setEntry('');setError('');const m:Message={id:uid('msg'),thread,role:'user',content:q,createdAt:new Date().toISOString()};const previous=messages;setMessages(old=>[...old,m]);await saveMessage(m);setBusy(true);
 try{const out=await askBrief(q,profile,applications,previous,chatJob||undefined);const answer:Message={id:uid('msg'),thread,role:'assistant',content:out,createdAt:new Date().toISOString()};await saveMessage(answer);setMessages(old=>[...old,answer]);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <KeyboardAvoidingView style={{flex:1}} behavior="padding" keyboardVerticalOffset={insets.top+59}>
 <View style={{paddingHorizontal:18,paddingBottom:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><View style={{flex:1}}><Heading>Ask Brief</Heading><Txt color={C.muted} size={12} style={{flexShrink:1}}>{chatJob?chatJob.title+' · '+chatJob.company:'Your on-device job search companion'}</Txt></View>{!kb&&<View style={{backgroundColor:C.pale,borderRadius:45,padding:6}}><Mascot size={66}/></View>}</View>
 <ScrollView ref={scroll} keyboardShouldPersistTaps="handled" onContentSizeChange={()=>scroll.current?.scrollToEnd({animated:true})} contentContainerStyle={{paddingHorizontal:16,paddingBottom:12,gap:12,flexGrow:1,justifyContent:'flex-end'}}>
 {messages.length===0&&<Card><Txt color={C.muted}>{chatJob?'Ask anything about this job: red flags, what to ask HR, or whether you fit.':'Ask about your saved jobs, red flags, your resume, or interview prep.'} Messages stay on this device.</Txt></Card>}
 {messages.map(m=><View key={m.id} style={{maxWidth:'88%',alignSelf:m.role==='user'?'flex-end':'flex-start',flexDirection:'row',alignItems:'flex-end',gap:7}}>{m.role==='assistant'&&<Mascot size={31}/>}<View style={{backgroundColor:m.role==='user'?C.blue:C.pale,padding:13,borderRadius:18,flexShrink:1}}><Txt color={m.role==='user'?C.white:C.ink}>{m.content}</Txt></View></View>)}
 {busy&&<ActivityIndicator color={C.blue} accessibilityLabel="Brief is thinking"/>}
 {!!error&&<Card style={{gap:10}}><Txt color={C.danger}>{error}</Txt>{error===MODEL_MISSING&&<Primary secondary label="Open Settings" onPress={()=>go('settings')}/>}</Card>}
 </ScrollView>
 <View style={{paddingHorizontal:15,gap:8,paddingBottom:kb?8:insets.bottom+82}}><ScrollView horizontal keyboardShouldPersistTaps="handled" showsHorizontalScrollIndicator={false} style={{flexGrow:0}} contentContainerStyle={{gap:7}}>{CHIPS.map(x=><Pressable key={x} accessibilityRole="button" disabled={busy} onPress={()=>void send(x)} style={{borderRadius:22,backgroundColor:C.pale,paddingHorizontal:12,paddingVertical:10}}><Txt color={C.blue} size={12}>{x}</Txt></Pressable>)}</ScrollView>
 <View style={{backgroundColor:C.white,borderRadius:28,borderWidth:1,borderColor:C.line,padding:6,flexDirection:'row',alignItems:'center',gap:7}}><TextInput accessibilityLabel="Message Brief" value={entry} onChangeText={setEntry} placeholder="Message Brief..." placeholderTextColor={C.soft} style={{padding:8,flex:1,color:C.ink,maxHeight:120}} multiline/><Pressable accessibilityRole="button" accessibilityLabel="Send" disabled={busy||!entry.trim()} onPress={()=>void send()} style={{width:40,height:40,backgroundColor:C.blue,opacity:busy||!entry.trim()?.5:1,borderRadius:20,alignItems:'center',justifyContent:'center'}}><Icon name="arrow-up" color={C.white}/></Pressable></View>
 </View></KeyboardAvoidingView>;
}
