import React,{useEffect,useRef,useState} from 'react';import {ActivityIndicator,Alert,KeyboardAvoidingView,Platform,Pressable,ScrollView,TextInput,View} from 'react-native';
import {useBrief} from '../lib/appContext';import {uid,listMessages,saveMessage} from '../lib/db';import {askBrief} from '../lib/ai';import {C} from '../theme/tokens';import {Card,Heading,Icon,Mascot,Txt} from '../components/Ui';import type {Message} from '../types';
export function ChatScreen(){const {profile,applications,chatJob}=useBrief();const thread=chatJob?'job:'+chatJob.id:'general';
 const [messages,setMessages]=useState<Message[]>([]),[entry,setEntry]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const scroll=useRef<ScrollView>(null);
 useEffect(()=>{void listMessages(thread).then(setMessages);},[thread]);
 async function send(text=entry){const q=text.trim();if(!q||busy)return;setEntry('');setError('');const m:Message={id:uid('msg'),thread,role:'user',content:q,createdAt:new Date().toISOString()};const previous=messages;setMessages(old=>[...old,m]);await saveMessage(m);setBusy(true);
 try{const out=await askBrief(q,profile,applications,previous,chatJob||undefined);const answer:Message={id:uid('msg'),thread,role:'assistant',content:out,createdAt:new Date().toISOString()};await saveMessage(answer);setMessages(old=>[...old,answer]);}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined} keyboardVerticalOffset={68}>
 <View style={{paddingHorizontal:18,paddingBottom:11,flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><View><Heading>Ask Brief</Heading><Txt color={C.muted} size={12}>{chatJob?chatJob.title+' · '+chatJob.company:'Your local AI job companion'}</Txt></View><Mascot size={70}/></View>
 <ScrollView ref={scroll} onContentSizeChange={()=>scroll.current?.scrollToEnd({animated:true})} contentContainerStyle={{paddingHorizontal:16,paddingBottom:18,gap:12,flexGrow:1,justifyContent:'flex-end'}}>
 {messages.length===0&&<Card><Txt color={C.muted}>Ask about saved jobs, red flags, your resume, or interview preparation. Your messages remain on this device.</Txt></Card>}
 {messages.map(m=><View key={m.id} style={{maxWidth:'88%',alignSelf:m.role==='user'?'flex-end':'flex-start',flexDirection:'row',alignItems:'flex-end',gap:7}}>{m.role==='assistant'&&<Mascot size={31}/>}<View style={{backgroundColor:m.role==='user'?C.blue:C.pale2,padding:13,borderRadius:18,flexShrink:1}}><Txt color={m.role==='user'?C.white:C.ink}>{m.content}</Txt></View></View>)}
 {busy&&<ActivityIndicator color={C.blue}/>} {!!error&&<Card><Txt color={C.danger}>{error}</Txt></Card>}
 </ScrollView>
 <View style={{paddingHorizontal:15,gap:8,paddingBottom:90}}><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{flexGrow:0}} contentContainerStyle={{gap:7}}>{['What should I ask?','Is this a red flag?','Am I qualified?'].map(x=><Pressable key={x} onPress={()=>void send(x)} style={{borderRadius:22,backgroundColor:C.pale,padding:9}}><Txt color={C.blue} size={11}>{x}</Txt></Pressable>)}</ScrollView>
 <View style={{backgroundColor:C.white,borderRadius:28,borderWidth:1,borderColor:C.line,padding:7,flexDirection:'row',alignItems:'center',gap:7}}><TextInput value={entry} onChangeText={setEntry} placeholder="Message Brief..." placeholderTextColor={C.soft} style={{padding:7,flex:1,color:C.ink}} multiline/><Pressable disabled={busy} onPress={()=>void send()} style={{width:36,height:36,backgroundColor:C.blue,borderRadius:19,alignItems:'center',justifyContent:'center'}}><Icon name="arrow-up" color={C.white}/></Pressable></View>
 </View></KeyboardAvoidingView>;
}
