import React,{useEffect,useState,useRef} from 'react';
import {ActivityIndicator,KeyboardAvoidingView,Platform,Pressable,ScrollView,TextInput,View} from 'react-native';
import {useBrief} from '../lib/appContext';import {uid,saveMessage,listMessages} from '../lib/db';import {mockInterview} from '../lib/ai';import {C} from '../theme/tokens';
import {Icon,Mascot,Primary,Txt} from '../components/Ui';import type {Application,Message} from '../types';
export function MockScreen(){const {applications,profile}=useBrief();const [job,setJob]=useState<Application|null>(null),[messages,setMessages]=useState<Message[]>([]),[value,setValue]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const scroll=useRef<ScrollView>(null);
 const thread=job?'mock:'+job.id:'mock:none';
 useEffect(()=>{if(job){void listMessages(thread).then(setMessages);}else setMessages([]);},[thread]);
 async function send(text:string,finish=false){if(!job||busy)return;setError('');setBusy(true);const history=messages;const m:Message={id:uid('mock'),role:'user',content:text,thread,createdAt:new Date().toISOString()};setMessages(old=>[...old,m]);await saveMessage(m);setValue('');
 try{const out=await mockInterview(text,profile,job,history,finish);const assistant:Message={id:uid('mock'),role:'assistant',content:out,thread,createdAt:new Date().toISOString()};await saveMessage(assistant);setMessages(old=>[...old,assistant]);}catch(e){setError(String(e));}finally{setBusy(false);}}
 if(!job)return <ScrollView contentContainerStyle={{padding:20,paddingBottom:115,alignItems:'center',gap:18}}><View style={{backgroundColor:C.pale,borderRadius:95,padding:20,marginTop:25}}><Mascot size={165}/></View><Txt size={19} bold>Who are you interviewing for?</Txt><Txt color={C.muted} style={{textAlign:'center'}}>Choose a saved application to begin a local AI mock interview.</Txt><View style={{width:'100%',gap:8}}>{applications.length===0?<Txt color={C.muted}>Add a job first with the + button.</Txt>:applications.map(a=><Pressable key={a.id} onPress={()=>{setJob(a);setMessages([]);}} style={{padding:15,backgroundColor:C.white,borderColor:C.line,borderWidth:1,borderRadius:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><View><Txt bold>{a.company}</Txt><Txt color={C.muted} size={12}>{a.title}</Txt></View><Icon name="chevron-forward" color={C.blue}/></Pressable>)}</View></ScrollView>;
 return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined} keyboardVerticalOffset={65}>
 <View style={{alignItems:'center',paddingTop:2}}><Mascot size={115}/><Pressable onPress={()=>setJob(null)}><Txt color={C.blue} size={12}>‹ Change company · {job.company}</Txt></Pressable></View>
 <ScrollView ref={scroll} onContentSizeChange={()=>scroll.current?.scrollToEnd({animated:true})} contentContainerStyle={{flexGrow:1,justifyContent:'flex-end',gap:9,padding:15,paddingBottom:14}}>
 {messages.length===0&&<Pressable onPress={()=>void send('Begin the interview with your first question.')} style={{backgroundColor:C.pale,padding:14,borderRadius:17}}><Txt bold>Ready to practice?</Txt><Txt color={C.muted}>Tap here to start your local AI interview.</Txt></Pressable>}
 {messages.map(m=><View key={m.id} style={{alignSelf:m.role==='user'?'flex-end':'flex-start',maxWidth:'87%',flexDirection:'row',gap:6,alignItems:'flex-end'}}>{m.role==='assistant'&&<Mascot size={29}/>}<View style={{padding:13,backgroundColor:m.role==='user'?C.blue:C.pale2,borderRadius:16,flexShrink:1}}><Txt color={m.role==='user'?C.white:C.ink}>{m.content}</Txt></View></View>)}
 {busy&&<ActivityIndicator color={C.blue}/>} {!!error&&<Txt color={C.danger}>{error}</Txt>}
 </ScrollView>
 <View style={{paddingHorizontal:17,paddingBottom:91,gap:7}}><View style={{flexDirection:'row',gap:9}}><Pressable onPress={()=>void send('Please end this interview and give me specific overall feedback.',true)}><Txt color={C.blue} size={12}>Finish & feedback</Txt></Pressable></View><View style={{flexDirection:'row',backgroundColor:C.white,borderRadius:22,alignItems:'center',padding:8,borderWidth:1,borderColor:C.line}}><TextInput value={value} onChangeText={setValue} style={{flex:1,padding:8,color:C.ink}} placeholder="Your answer..." placeholderTextColor={C.soft} multiline/><Pressable disabled={busy} onPress={()=>void send(value)} style={{backgroundColor:C.blue,borderRadius:17,padding:10}}><Icon name="arrow-up" color={C.white}/></Pressable></View></View>
 </KeyboardAvoidingView>;
}
