import React,{useEffect,useState} from 'react';
import { Image, Keyboard, Pressable, Text, TextInput, View, type StyleProp, type ViewStyle } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { C,R } from '../theme/tokens';
export function Icon({name,size=20,color=C.ink}:{name:string,size?:number,color?:string}) {return <Ionicons name={name as any} size={size} color={color}/>;}
export function Txt({children,size=14,bold=false,color=C.ink,style}:{children:React.ReactNode,size?:number,bold?:boolean,color?:string,style?:any}) {return <Text style={[{fontSize:size,fontWeight:bold?'700':'400',color,lineHeight:size*1.37},style]}>{children}</Text>}
export function Heading({children}:{children:React.ReactNode}) {return <Txt size={27} bold>{children}</Txt>}
export function Card({children,style}:{children:React.ReactNode,style?:StyleProp<ViewStyle>}) {return <View style={[{backgroundColor:C.white,borderRadius:R.card,padding:15,borderWidth:1,borderColor:C.line},style]}>{children}</View>}
export function Primary({label,onPress,secondary=false,disabled=false}:{label:string,onPress:()=>void,secondary?:boolean,disabled?:boolean}) {return <Pressable accessibilityRole="button" onPress={onPress} disabled={disabled} style={{paddingVertical:13,paddingHorizontal:16,backgroundColor:secondary?C.pale:C.blue,borderRadius:13,opacity:disabled?.55:1,alignItems:'center'}}><Txt color={secondary?C.blue:C.white} bold>{label}</Txt></Pressable>}
export function Input({value,onChangeText,placeholder,multiline=false}:{value:string,onChangeText:(text:string)=>void,placeholder?:string,multiline?:boolean}) {return <TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={C.soft} multiline={multiline} style={{backgroundColor:C.pale2,color:C.ink,borderRadius:12,padding:12,marginTop:5,minHeight:multiline?100:45,textAlignVertical:multiline?'top':'center',fontSize:14}}/>}
export function Field({label,value,onChangeText,placeholder,multiline}:{label:string,value:string,onChangeText:(v:string)=>void,placeholder?:string,multiline?:boolean}) {return <View style={{marginBottom:11}}><Txt size={12} color={C.muted}>{label}</Txt><Input {...{value,onChangeText,placeholder,multiline}}/></View>}
export function SmallIconButton({icon,onPress}:{icon:string,onPress:()=>void}) {return <Pressable onPress={onPress} hitSlop={10} style={{width:36,height:36,alignItems:'center',justifyContent:'center',borderRadius:18,backgroundColor:C.pale2}}><Icon name={icon} color={C.blue} size={18}/></Pressable>}
export function Mascot({size=125}:{size?:number}) {return <Image source={require('../../assets/mascot-happy.png')} resizeMode="contain" style={{width:size,height:size}}/>}
export function Brand({onPress}:{onPress?:()=>void}) {return <Pressable onPress={onPress} style={{flexDirection:'row',alignItems:'center',gap:2}}><Txt bold size={29} color="#050505" style={{letterSpacing:-2}}>brief</Txt><Mascot size={32}/></Pressable>}
export function StatusPill({status}:{status:string}) { const label:{[k:string]:string}={saved:'Saved',interested:'Interested',applied:'Applied',interview:'Interview',under_review:'Under review',offer:'Offer',rejected:'Rejected'};const green=['applied','offer'].includes(status); return <View style={{paddingHorizontal:10,paddingVertical:5,borderRadius:20,backgroundColor:green?C.greenSoft:status==='rejected'?C.redSoft:C.pale}}><Txt size={11} color={green?C.green:status==='rejected'?C.danger:C.blue}>{label[status]||status}</Txt></View>}
export function SectionTitle({children,right,onRight}:{children:string,right?:string,onRight?:()=>void}) {return <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:9}}><Txt size={17} bold>{children}</Txt>{right&&<Pressable onPress={onRight}><Txt size={13} color={C.blue}>{right}</Txt></Pressable>}</View>}
/** True while the software keyboard is up; the floating bar hides so it never covers a composer. */
export function useKeyboardVisible() {const [v,setV]=useState(false);useEffect(()=>{const a=Keyboard.addListener('keyboardDidShow',()=>setV(true)),b=Keyboard.addListener('keyboardDidHide',()=>setV(false));return ()=>{a.remove();b.remove();};},[]);return v;}
